### ISSUE TITLE
missing README

### ISSUE THREAD

**Issue by lgg** [TakenOrNot/badassplanestheme#1]
Hi, found your post on Reddit. Please, can you add README.md for this repo with description and screenshots?

**Comment by wight-airmash** [comment]
Not exactly on the issue subject: if it's referring to [this post](https://www.reddit.com/r/airmash/comments/frhujd/set_up_new_graphics_or_more_on_airmashonline_or/), here's an [author](https://github.com/xvalyagamemaker2039).
